/** LCP preload — AVIF first, WebP fallback (generated by scripts/optimize-hero-images.mjs). */
export function HeroImagePreload() {
    return (
        <>
            <link
                rel="preload"
                as="image"
                href="/images/blog/hero-sunset.avif"
                type="image/avif"
                fetchPriority="high"
                media="(min-width: 1024px)"
            />
            <link
                rel="preload"
                as="image"
                href="/images/blog/hero-sunset-mobile.avif"
                type="image/avif"
                fetchPriority="high"
                media="(max-width: 1023px)"
            />
        </>
    );
}
